image: mcr.microsoft.com/dotnet/sdk:5.0

pipelines:
  default:
    - parallel:
        - step:
#            runs-on: self.hosted
            name: Build and Test
            caches:
              - dotnetcore
            script:
              - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
              - dotnet restore Projeto.sln
              - dotnet build Projeto.sln --no-restore --configuration Release
              - dotnet test Projeto.sln --no-build --configuration Release --test-adapter-path:. 
#        - step:
#            name: Lint the code
#            caches:
#              - dotnetcore
#            script:
#              - export SOLUTION_NAME=Projeto
#              - export REPORTS_PATH=linter-reports
#              - dotnet new tool-manifest
#              - dotnet tool install JetBrains.ReSharper.GlobalTools
#              - dotnet tool restore
#              - dotnet jb inspectcode ${SOLUTION_NAME}.sln # output="${REPORTS_PATH}/jb-${BITBUCKET_BUILD_NUMBER}.xml"
#            artifacts:
#             - linter-reports/**
